server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://124.222.253.95:3306/ibook?useSSL=false
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl