# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: deploy aliyun

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.inputs.branch }}
          
    - name: Build with Maven
      run: mvn  package --file pom.xml

    - name: scp uat file to uat ecs
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        password: ${{ secrets.PASSWORD }}
        source: "./target/ibook-0.0.1-SNAPSHOT.jar"
        target: "/hyy/ibook"
